version: 2.1

jobs:
  terraform-deploy:
    docker:
      - image: hashicorp/terraform:latest  

    environment:
      AWS_REGION: "us-east-1"  # Ensure the region is set

    steps:
      - checkout  

      - run:
          name: "Terraform Init"
          command: terraform init

      - run:
          name: "Terraform Plan"
          command: terraform plan -out=tfplan

      - run:
          name: "Terraform Apply"
          command: terraform apply -auto-approve tfplan

workflows:
  terraform-workflow:
    jobs:
      - terraform-deploy

