version: 2.1

jobs:
  terraform-deploy:
    docker:
      - image: hashicorp/terraform:latest  # Use Terraform's official image

    steps:
      - checkout  # Checkout the code repository

      - run:
          name: "Install Dependencies"
          command: |
            apk add --no-cache curl jq git  # Install necessary packages

      - run:
          name: "Terraform Init"
          command: terraform init

      - run:
          name: "Terraform Plan"
          command: terraform plan -out=tfplan

      - run:
          name: "Terraform Apply"
          command: terraform apply -auto-approve tfplan

workflows:
  terraform-workflow:
    jobs:
      - terraform-deploy
